title: Suelen Cristina # your name (or website title) here
logo: "/images/circle-cropped (2).png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Python developer and Data scientist<br>
  <br><br>
Experienced in creating and database analysis, being able to synthesize quantitative information and interact effectively with colleagues and customers. Capable of receiving and monitoring data from sources such as SQL and Excel. 
I'm passionate about using the data science skills I've developed to help people and make a concrete positive impact on the world.
  <br><br>
  <br><br>
  teste
  <br><br>
  <a href="https://www.linkedin.com/in/data-by-su/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
